
package cl.ubb.testing.safeit.exceptions;

public class UsuarioNotFoundException extends Exception {
	public UsuarioNotFoundException() {
		super();
	}
}
