package cl.ubb.testing.safeit.exceptions;

public class UsuarioErrorException extends Exception{

}
