package cl.ubb.testing.safeit.exception;

public class UsuarioErrorException extends Exception{

}
